export TERMINAL="iterm2"
export EDITOR="nvim"


export PATH=$PATH:/usr/local/opt/ruby/bin:/Users/codex/.local/bin
. "$HOME/.cargo/env"

export HOMEBREW_NO_ENV_HINTS=true

export LEMMINX_HOME=$HOME/Workspace/nvim-lsp/lemminx-server
