git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="OneHalfDark"
gui:
  language: "zh-CN"
  nerdFontsVersion: "3"
  theme:
    # lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - cyan
    selectedLineBgColor:
      - "#05445c"
    selectedRangeBgColor:
      - blue
customCommands:
  - key: "C"
    command: "git czg"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
  - key: "<c-a>"
    command: "git czg ai -N=3"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
