git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --syntax-theme="OneHalfDark"
gui:
  language: "zh-CN"
  nerdFontsVersion: "3"
  theme:
    # lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - cyan
    selectedLineBgColor:
      - "#05445c"
    selectedRangeBgColor:
      - blue
